### ISSUE TITLE
[Bug]: Figure show issue

### ISSUE THREAD

**Issue by NPUZSY** [ROVI-org/thevenin#12]
### thevenin Version

0.1.1

### Python Version

3.10

### Describe the bug

When I use
`soln.plot('time_h', 'voltage_V')`
When drawing, figure cannot always be displayed on the screen. It must be added at the back
`plt.show()`
To really block the program

### Steps to Reproduce

```
import thevenin

model = thevenin.Model()

expr = thevenin.Experiment()
expr.add_step('current_A', 75., (3600., 1.), limits=('voltage_V', 3.))

soln = model.run(expr)
soln.plot('time_h', 'voltage_V')
# plt.show()
```

**Comment by c-randall** [comment]
This issue has been addressed in the v0.1.2 release. Note that this is the old repo for `thevenin`. The new main repository is now hosted under the NREL organization. This repo will only stay open for a few more months to help with a transition period. 

You can install v0.1.2 from PyPI by using `pip install thevenin`. If you want to keep up with new development, please follow the new repo [here](https://github.com/NREL/thevenin) instead.
